"""Train/export a small neural regression model on synthetic data only."""
from pathlib import Path
import sys,json
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error,r2_score
from src.data_collection import generate_mof_dataset
features=['Surface_Area','Pore_Volume','Framework_Density','Pore_Diameter','Void_Fraction','Has_Amino_Group']
df=generate_mof_dataset(3000);X=df[features].to_numpy();y=df.CO2_Adsorption_mol_kg.to_numpy()
train,test=train_test_split(np.arange(len(df)),test_size=.2,random_state=42);scaler=StandardScaler().fit(X[train]);a=scaler.transform(X[train]);b=scaler.transform(X[test]);net=MLPRegressor(hidden_layer_sizes=(32,16),max_iter=800,random_state=42,early_stopping=True).fit(a,y[train]);ridge=Ridge().fit(a,y[train]);prediction=net.predict(b)
report={'dataset':'Synthetic generator; not experimental data','conditions':'Generator target: CO2 mol/kg at 298 K and 1 bar','train_rows':len(train),'test_rows':len(test),'seed':42,'neural_mae':float(mean_absolute_error(y[test],prediction)),'neural_r2':float(r2_score(y[test],prediction)),'ridge_mae':float(mean_absolute_error(y[test],ridge.predict(b))),'ridge_r2':float(r2_score(y[test],ridge.predict(b))),'residual_90_percent':float(np.quantile(abs(prediction-y[test]),.9))}
out=ROOT/'web';out.mkdir(exist_ok=True);(out/'model.json').write_text(json.dumps({'features':features,'mean':scaler.mean_.tolist(),'scale':scaler.scale_.tolist(),'weights':[w.tolist() for w in net.coefs_],'biases':[b.tolist() for b in net.intercepts_],'ranges':np.array([X.min(axis=0),X.max(axis=0)]).T.tolist(),'report':report}))
(ROOT/'docs').mkdir(exist_ok=True);(ROOT/'docs/browser_model.md').write_text('# Learned browser model\n\n`python scripts/train_browser_model.py` trains a scikit-learn MLP regressor on 3,000 synthetic records generated by the existing repository code and exports weights, scaler parameters, input ranges and held-out metrics to `web/model.json`. Browser predictions perform the same scaled dense-layer operations, rather than a hand-written scoring formula.\n\nThe 80/20 split uses seed 42. A Ridge regression baseline is evaluated on the identical test rows. The model estimates the generator, not experimentally measured adsorption. The residual band is an empirical synthetic-test statistic, not a calibrated interval for real materials. The selected six input features match the generator target.\n\nNIST experimental isotherm and JARVIS hMOF downloads were investigated; their download endpoints were unavailable during this run. An experimental or published simulation dataset with matched descriptors and pressure/temperature conditions is required before scientific generalization claims.\n\nSources: https://adsorption.nist.gov/ and https://pages.nist.gov/jarvis/databases/\n')
print(json.dumps(report))
